### ISSUE TITLE
Not autogrowing textarea not visble

### ISSUE THREAD

**Issue by sebasladino** [ultimatedelman/autogrow#32]
Hi, i have a textarea into of a modal bootstrap, via js initialize this textarea with autogrow but this not auto resize, i think this happens because this texarea is visible only modal launch. Any solution to this.

Thanks.

**Comment by jeferson-hernandez08** [comment]
Hello My Brother, 
El textarea no se redimensiona porque el modal estaba oculto cuando se calculó su tamaño.
La solución es recalcular altura cuando el modal se muestra.
