### ISSUE TITLE
jQuery 3 compatibility - error in the resize function

### ISSUE THREAD

**Issue by gunjangupta** [ultimatedelman/autogrow#36]
We recently upgraded to jQuery 3.1.0
Now we are getting the following error when we backspace in a textbox, which is strange because we are using autogrow on textareas only.

> Unable to get property 'ownerDocument' of undefined or null reference

The error happens on 
`clone = box.clone()
                            //add clone class for extra css rules
                            .addClass(opts.cloneClass)
                            //make "invisible", remove height restriction potentially imposed by existing CSS
                            .css({ position: 'absolute', zIndex: -10, height: '' })
                            //populate with content for consistent measuring
                            .val(box.val());`

**Comment by ultimatedelman** [comment]
My guess would be to check your code. I don't think there's any attempt to
access `ownerDocument` anywhere within autogrow.

**Comment by gunjangupta** [comment]
ownerDocument is referenced in the jQuery3 code. So, the box.clone() is resulting in the error in the jQuery code. 
We ended up switching to a different plugin because of some other constraints, so I'm closing this issue.
